# Generated by Django 5.2.5 on 2025-08-24 00:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("file", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="File",
            new_name="FileModel",
        ),
    ]
